version: '3.7'

name: "Backend"

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      network: host
    container_name: app
    ports:
      - 8000:8000
    restart: unless-stopped
    env_file: .env
    volumes:
        - ../log:/var/log
        - ../../data:/backend/data

networks:
  host:
    name: host
    external: true
